CREATE TABLE IF NOT EXISTS benefits (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  benefit_type INTEGER,
  activated_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

